# Generated by Django 4.1.7 on 2023-03-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_requestcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcount',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
